# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	libexcal_color_ctrl_plugin \
	libexcal_debug_display_plugin \
	libexcal_exposure_ctrl_plugin \
	libexcal_face_detector_plugin \
	libexcal_flicker_detector_plugin \
	libexcal_focus_stats_conv_plugin \
	libexcal_food_comp_plugin \
	libexcal_food_detector_plugin \
	libexcal_hal_ctrl_plugin \
	libexcal_hdr_plugin \
	libexcal_idt_ctrl_plugin \
	libexcal_image_conv_plugin \
	libexcal_iq_ctrl_plugin \
	libexcal_jpeg_enc_plugin \
	libexcal_lens_ctrl_plugin \
	libexcal_motion_estimation_plugin \
	libexcal_multiframe_nr_plugin \
	libexcal_object_tracker_plugin \
	libexcal_req_ctrl_plugin \
	libexcal_scene_detector_plugin \
	libexcal_snapshot_ctrl_plugin \
	libexcal_splitter_plugin \
	libexcal_stream_ctrl_plugin \
	libdrmwvmplugin \
	camera.msm8994 \
	libMcClient \
	lib_asb_tee \
	libcacao_client \
	libcacao_common \
	libcacao_imgproc \
	libcacao_jpeg \
	libcacao_service \
	libcacao_system \
	libcamera_clientsemc \
	libcameraextensionclient \
	libcameraextensionjni \
	libcameraextensionservice \
	libcameralight \
	libcammw \
	libcredential-manager-service \
	libdeqp_somc \
	libdevice_security \
	libexcal_core \
	libexcal_legacy \
	libexcal_pal \
	libexcal_system \
	libhdcprx_module \
	libidd \
	libmm-qcamera \
	libmmcamera_interface \
	libmmjpeg_interface \
	liboemcrypto \
	libpin-cache \
	libplstorage \
	libprotobuf-c \
	libqomx_core \
	libscdclient \
	libsomc_alfort \
	libsomc_alfortrsc \
	libsomc_bordeaux \
	libsomc_bordeauxrsc \
	libsomc_canele \
	libsomc_canelersc \
	libsomc_chokoballcmn \
	libsomc_chokoballpal \
	libsomc_marble \
	libsomc_marblersc \
	libsomc_melonpan \
	libsomc_melonpanrsc \
	libsomc_mugichoco \
	libsomc_mugichocorsc \
	libsomc_raisin \
	libsomc_raisinrsc \
	libsomc_spica \
	libsomc_spicarsc \
	libsomc_thermal \
	libsomc_toppo \
	libsomc_topporsc \
	libsomc_yummy \
	libsomc_yummyrsc \
	libsomcavextensionsimpl \
	libsomcmediahttp \
	libsony_fooddetect \
	libsony_naruto \
	libstagefright_soft_somcalacdec \
	libstagefright_soft_somcdsddec \
	libsuntory \
	libsuntory_utils \
	libta \
	libwebviewsomc_plat_support \
	eglSubDriverAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libQTapGLES \
	libq3dtools_adreno \
	libq3dtools_esx \
	lib-imscamera \
	lib-imss \
	lib-imsvt \
	lib-imsxml \
	lib-sec-disp \
	libC2D2 \
	libCB \
	libExtendedExtractor \
	libFIDOKeyProvisioning \
	libFidoCrypto \
	libFidoCryptoJNI \
	libFileMux \
	libFlacSwDec \
	libI420colorconvert \
	libOmxAacDec \
	libOmxAmrwbplusDec \
	libOmxEvrcDec \
	libOmxMux \
	libOmxQcelp13Dec \
	libOmxWmaDec \
	libOpenCL \
	libQSEEComAPI \
	libRSDriver_adreno \
	libStDrvInt \
	libWVStreamControlAPI_L1 \
	libacdb-fts \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libactuator_ad5823 \
	libactuator_ad5823_camcorder \
	libactuator_ad5823_camera \
	libactuator_bu64244gwz \
	libactuator_bu64244gwz_camcorder \
	libactuator_bu64244gwz_camera \
	libactuator_dw9714 \
	libactuator_dw9714_camcorder \
	libactuator_dw9714_camera \
	libactuator_dw9716 \
	libactuator_dw9716_camcorder \
	libactuator_dw9716_camera \
	libactuator_dw9761b \
	libactuator_dw9761b_camcorder \
	libactuator_dw9761b_camera \
	libactuator_lc898122 \
	libactuator_lc898122_camcorder \
	libactuator_lc898122_camera \
	libactuator_lc898212xd \
	libactuator_lc898212xd_camcorder \
	libactuator_lc898212xd_camera \
	libactuator_ov8825 \
	libactuator_ov8825_camcorder \
	libactuator_ov8825_camera \
	libactuator_rohm_bu64243gwz \
	libactuator_rohm_bu64243gwz_camcorder \
	libactuator_rohm_bu64243gwz_camera \
	libadiertac \
	libadm \
	libadreno_utils \
	libadsprpc \
	libaudcal \
	libaudioalsa \
	libavenhancements \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libchromaflash \
	libchromatix_s5k3m2xx_common \
	libchromatix_s5k3m2xx_cpp_hfr_120 \
	libchromatix_s5k3m2xx_cpp_hfr_60 \
	libchromatix_s5k3m2xx_cpp_hfr_90 \
	libchromatix_s5k3m2xx_cpp_liveshot \
	libchromatix_s5k3m2xx_cpp_preview \
	libchromatix_s5k3m2xx_cpp_snapshot \
	libchromatix_s5k3m2xx_cpp_video \
	libchromatix_s5k3m2xx_cpp_video_4k \
	libchromatix_s5k3m2xx_default_video \
	libchromatix_s5k3m2xx_hfr_120 \
	libchromatix_s5k3m2xx_hfr_60 \
	libchromatix_s5k3m2xx_hfr_90 \
	libchromatix_s5k3m2xx_liveshot \
	libchromatix_s5k3m2xx_postproc \
	libchromatix_s5k3m2xx_preview \
	libchromatix_s5k3m2xx_snapshot \
	libchromatix_s5k3m2xx_video_4k \
	libdataitems \
	libdrmclearkeyplugin \
	libdrmfs \
	libdrmtime \
	libfastcvadsp_stub \
	libfastcvopt \
	libflash_pmic \
	libgsl \
	libhwdaphal \
	libimscamera_jni \
	libjpegdhw \
	libjpegdmahw \
	libjpegehw \
	libllvd_smore \
	libllvm-glnext \
	libllvm-qcom \
	libmdmdetect \
	libmdsprpc \
	libmm-abl-oem \
	libmm-abl \
	libmm-als \
	libmm-color-convertor \
	libmm-disp-apis \
	libmm-hdcpmgr \
	libmm-qdcm \
	libmmQSM \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_frame_algorithm \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_is \
	libmmcamera2_isp_modules \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_q3a_core \
	libmmcamera2_sensor_debug \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_algorithm \
	libmmcamera2_stats_modules \
	libmmcamera2_vpe_module \
	libmmcamera2_wnr_module \
	libmmcamera_cac2_lib \
	libmmcamera_chromaflash_lib \
	libmmcamera_dw9761b_eeprom \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_faceproc \
	libmmcamera_hdr_gb_lib \
	libmmcamera_imglib \
	libmmcamera_imx258_gt24c16_eeprom \
	libmmcamera_isp_abf44 \
	libmmcamera_isp_bcc44 \
	libmmcamera_isp_be_stats44 \
	libmmcamera_isp_bf_scale_stats46 \
	libmmcamera_isp_bf_stats44 \
	libmmcamera_isp_bg_stats46 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_bpc44 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_clf46 \
	libmmcamera_isp_color_correct46 \
	libmmcamera_isp_color_xform_encoder46 \
	libmmcamera_isp_color_xform_video46 \
	libmmcamera_isp_color_xform_viewfinder46 \
	libmmcamera_isp_cs_stats46 \
	libmmcamera_isp_demosaic44 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder46 \
	libmmcamera_isp_fovcrop_video46 \
	libmmcamera_isp_fovcrop_viewfinder46 \
	libmmcamera_isp_gamma44 \
	libmmcamera_isp_gic46 \
	libmmcamera_isp_gtm46 \
	libmmcamera_isp_hdr46 \
	libmmcamera_isp_hdr_be_stats46 \
	libmmcamera_isp_ihist_stats46 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_ltm44 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff44 \
	libmmcamera_isp_pedestal_correct46 \
	libmmcamera_isp_rs_stats46 \
	libmmcamera_isp_scaler_encoder46 \
	libmmcamera_isp_scaler_video46 \
	libmmcamera_isp_scaler_viewfinder46 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_sub_module \
	libmmcamera_isp_wb46 \
	libmmcamera_llvd \
	libmmcamera_onsemi_cat24c32_eeprom \
	libmmcamera_optizoom_lib \
	libmmcamera_ov4688_eeprom \
	libmmcamera_pdaf \
	libmmcamera_pdaf_v3 \
	libmmcamera_pdafcamif \
	libmmcamera_ppbase_module \
	libmmcamera_sony_imx214_eeprom \
	libmmcamera_sonyimx135_eeprom \
	libmmcamera_stillmore_lib \
	libmmcamera_tintless_algo \
	libmmcamera_tintless_bg_pca_algo \
	libmmcamera_trueportrait_lib \
	libmmcamera_tuning \
	libmmcamera_ubifocus_lib \
	libmmcamera_vpu_module \
	libmmhttpstack \
	libmmiipstreammmihttp \
	libmmipl \
	libmmipstreamaal \
	libmmipstreamnetwork \
	libmmipstreamsourcehttp \
	libmmipstreamutils \
	libmmjpeg \
	libmmosal \
	libmmparser \
	libmmparser_lite \
	libmmqjpeg_codec \
	libmmqjpegdma \
	libmmrtpdecoder \
	libmmrtpencoder \
	libmmwfdinterface \
	libmmwfdsinkinterface \
	libmmwfdsrcinterface \
	libnative_audio_latency_jni \
	liboemcamera \
	libois_lc898122 \
	libpreload-me \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	libqti-at \
	libqti-gt \
	libqti-perfd-client \
	libqti_performance \
	librpmb \
	librs_adreno \
	librs_adreno_sha1 \
	libscale \
	libsecureui \
	libsecureui_svcsock \
	libsensor1 \
	libsensor_reg \
	libssd \
	libsurround_3mic_proc \
	libts_detected_face_jni \
	libts_face_beautify_jni \
	libtzdrmgenprov \
	libwfdavenhancements \
	libwfdcommonutils \
	libwfdmmsink \
	libwfdmmsrc \
	libwfdmmutils \
	libwfdnative \
	libwfdrtsp \
	libwfdservice \
	libwfdsm \
	libwfduibcinterface \
	libwfduibcsink \
	libwfduibcsinkinterface \
	libwfduibcsrc \
	libwfduibcsrcinterface \
	libwms \
	libwvdrm_L1 \
	libwvm \
	libwvdrmengine \
	fastrpc_shell_0 \
	libapps_mem_heap \
	libdspCV_skel \
	libfastcvadsp \
	libfastcvadsp_skel \
	sensors.ssc \
	libqcbassboost \
	libqcreverb \
	libqcvirt \
	libMcClient \
	lib_asb_tee \
	libcamera_clientsemc \
	libcameraextensionclient \
	libcameraextensionjni \
	libcameraextensionservice \
	libcameralight \
	libcredential-manager-service \
	libdeqp_somc \
	libdevice_security \
	libhdcprx_module \
	libidd \
	libpin-cache \
	libplstorage \
	libprotobuf-c \
	libscdclient \
	libsomc_thermal \
	libsomcavextensionsimpl \
	libsomcmediahttp \
	libsomcwifi-service \
	libsuntory \
	libsuntory_utils \
	libta \
	libtee \
	libwebviewsomc_plat_support \
	eglSubDriverAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libQTapGLES \
	libq3dtools_adreno \
	libq3dtools_esx \
	lib-imscamera \
	lib-imss \
	lib-imsvt \
	lib-imsxml \
	lib-preload64 \
	lib-sec-disp \
	libC2D2 \
	libCB \
	libExtendedExtractor \
	libFIDOKeyProvisioning \
	libFidoCrypto \
	libFidoCryptoJNI \
	libFileMux \
	libFlacSwDec \
	libI420colorconvert \
	libOmxAacDec \
	libOmxAmrwbplusDec \
	libOmxMux \
	libOmxWmaDec \
	libOpenCL \
	libQSEEComAPI \
	libRSDriver_adreno \
	libStDrvInt \
	libacdb-fts \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libadreno_utils \
	libadsprpc \
	libaudcal \
	libaudioalsa \
	libavenhancements \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libdataitems \
	libdrmclearkeyplugin \
	libdrmfs \
	libdrmtime \
	libgsl \
	libhwdaphal \
	libimscamera_jni \
	libllvm-glnext \
	libllvm-qcom \
	libmdmdetect \
	libmdsprpc \
	libmm-abl-oem \
	libmm-abl \
	libmm-als \
	libmm-color-convertor \
	libmm-disp-apis \
	libmm-hdcpmgr \
	libmm-qdcm \
	libmmQSM \
	libmmcamera2_q3a_core \
	libmmcamera2_sensor_debug \
	libmmcamera2_stats_algorithm \
	libmmhttpstack \
	libmmiipstreammmihttp \
	libmmipstreamaal \
	libmmipstreamnetwork \
	libmmipstreamsourcehttp \
	libmmipstreamutils \
	libmmosal \
	libmmparser \
	libmmparser_lite \
	libmmrtpdecoder \
	libmmrtpencoder \
	libmmwfdinterface \
	libmmwfdsinkinterface \
	libmmwfdsrcinterface \
	libpreload-me \
	libqti-perfd-client \
	libqti_performance \
	librpmb \
	librs_adreno \
	librs_adreno_sha1 \
	libscale \
	libsecureui \
	libsecureui_svcsock \
	libsensor1 \
	libsensor_reg \
	libssd \
	libtzdrmgenprov \
	libwfdavenhancements \
	libwfdcommonutils \
	libwfdmmsink \
	libwfdmmsrc \
	libwfdmmutils \
	libwfdnative \
	libwfdrtsp \
	libwfdservice \
	libwfdsm \
	libwfduibcinterface \
	libwfduibcsink \
	libwfduibcsinkinterface \
	libwfduibcsrc \
	libwfduibcsrcinterface \
	libwms \
	sensors.ssc \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	Sony_Bluetooth_cal \
	Sony_General_cal \
	Sony_Global_cal \
	Sony_Handset_cal \
	Sony_Hdmi_cal \
	Sony_Headset_cal \
	Sony_Speaker_cal \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	a420_pfp \
	a420_pm4 \
	cpp_firmware_v1_1_1 \
	cpp_firmware_v1_1_6 \
	cpp_firmware_v1_2_0 \
	cpp_firmware_v1_4_0 \
	cpp_firmware_v1_6_0 \
	cpp_firmware_v1_8_0 \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mdt \
	flashled_calc_parameters \
	hals \
	sensor_def_qcomdev \
	iddd \
	keyprovd \
	mm-qcamera-daemon \
	qseecomd \
	secd \
	sensors \
	taimport \
	updatemiscta \
	LGI05BN0_color_ctrl_dat \
	LGI05BN0_dataflow_dat \
	LGI05BN0_debug_mgr_dat \
	LGI05BN0_exposure_ctrl_dat \
	LGI05BN0_exposure_ctrl_diagram_dat \
	LGI05BN0_exposure_ctrl_gamma_dat \
	LGI05BN0_face_detector_dat \
	LGI05BN0_flicker_detector_dat \
	LGI05BN0_focus_stats_conv_dat \
	LGI05BN0_food_comp_yummy_dat \
	LGI05BN0_food_detector_dat \
	LGI05BN0_hal_ctrl_dat \
	LGI05BN0_hal_ctrl_platform_dat \
	LGI05BN0_hal_ctrl_platform_abf_dat \
	LGI05BN0_hal_ctrl_platform_asf_lin_dat \
	LGI05BN0_hal_ctrl_platform_asf_stp_dat \
	LGI05BN0_hal_ctrl_platform_gic_dat \
	LGI05BN0_hdr_comp_dat \
	LGI05BN0_idt_ctrl_dat \
	LGI05BN0_image_conv_dat \
	LGI05BN0_image_conv_canele_dat \
	LGI05BN0_image_conv_marble_dat \
	LGI05BN0_image_conv_raisin_dat \
	LGI05BN0_image_conv_spica_dat \
	LGI05BN0_jpeg_enc_dat \
	LGI05BN0_lens_ctrl_dat \
	LGI05BN0_motion_estimation_dat \
	LGI05BN0_multiframe_nr_dat \
	LGI05BN0_multiframe_nr_melonpan_dat \
	LGI05BN0_multiframe_nr_mugichoco_dat \
	LGI05BN0_multiframe_nr_toppo_dat \
	LGI05BN0_object_tracker_dat \
	LGI05BN0_scene_detector_dat \
	LGI05BN0_snapshot_ctrl_dat \
	LGI05BN0_IMX241 \
	SEM05BN0_color_ctrl_dat \
	SEM05BN0_dataflow_dat \
	SEM05BN0_debug_mgr_dat \
	SEM05BN0_exposure_ctrl_dat \
	SEM05BN0_exposure_ctrl_diagram_dat \
	SEM05BN0_exposure_ctrl_gamma_dat \
	SEM05BN0_face_detector_dat \
	SEM05BN0_flicker_detector_dat \
	SEM05BN0_focus_stats_conv_dat \
	SEM05BN0_food_comp_yummy_dat \
	SEM05BN0_food_detector_dat \
	SEM05BN0_hal_ctrl_dat \
	SEM05BN0_hal_ctrl_platform_dat \
	SEM05BN0_hal_ctrl_platform_abf_dat \
	SEM05BN0_hal_ctrl_platform_asf_lin_dat \
	SEM05BN0_hal_ctrl_platform_asf_stp_dat \
	SEM05BN0_hal_ctrl_platform_gic_dat \
	SEM05BN0_hdr_comp_dat \
	SEM05BN0_idt_ctrl_dat \
	SEM05BN0_image_conv_dat \
	SEM05BN0_image_conv_canele_dat \
	SEM05BN0_image_conv_marble_dat \
	SEM05BN0_image_conv_raisin_dat \
	SEM05BN0_image_conv_spica_dat \
	SEM05BN0_jpeg_enc_dat \
	SEM05BN0_lens_ctrl_dat \
	SEM05BN0_motion_estimation_dat \
	SEM05BN0_multiframe_nr_dat \
	SEM05BN0_multiframe_nr_melonpan_dat \
	SEM05BN0_multiframe_nr_mugichoco_dat \
	SEM05BN0_multiframe_nr_toppo_dat \
	SEM05BN0_object_tracker_dat \
	SEM05BN0_scene_detector_dat \
	SEM05BN0_snapshot_ctrl_dat \
	SEM05BN0_IMX241 \
	SOI25BS0_color_ctrl_dat \
	SOI25BS0_dataflow_dat \
	SOI25BS0_debug_mgr_dat \
	SOI25BS0_exposure_ctrl_dat \
	SOI25BS0_exposure_ctrl_diagram_dat \
	SOI25BS0_exposure_ctrl_gamma_dat \
	SOI25BS0_face_detector_dat \
	SOI25BS0_flicker_detector_dat \
	SOI25BS0_focus_stats_conv_dat \
	SOI25BS0_food_comp_yummy_dat \
	SOI25BS0_food_detector_dat \
	SOI25BS0_hal_ctrl_dat \
	SOI25BS0_hal_ctrl_platform_dat \
	SOI25BS0_hal_ctrl_platform_abf_dat \
	SOI25BS0_hal_ctrl_platform_asf_lin_dat \
	SOI25BS0_hal_ctrl_platform_asf_stp_dat \
	SOI25BS0_hal_ctrl_platform_gic_dat \
	SOI25BS0_hdr_comp_dat \
	SOI25BS0_idt_ctrl_dat \
	SOI25BS0_image_conv_dat \
	SOI25BS0_image_conv_canele_dat \
	SOI25BS0_image_conv_marble_dat \
	SOI25BS0_image_conv_raisin_dat \
	SOI25BS0_image_conv_spica_dat \
	SOI25BS0_jpeg_enc_dat \
	SOI25BS0_lens_ctrl_dat \
	SOI25BS0_motion_estimation_dat \
	SOI25BS0_multiframe_nr_dat \
	SOI25BS0_multiframe_nr_melonpan_dat \
	SOI25BS0_multiframe_nr_mugichoco_dat \
	SOI25BS0_multiframe_nr_toppo_dat \
	SOI25BS0_object_tracker_dat \
	SOI25BS0_scene_detector_dat \
	SOI25BS0_snapshot_ctrl_dat \
	SOI25BS0_BU64747GWZ \
	SOI25BS0_BU64747GWZ_XCF \
	SOI25BS0_BU64747GWZ_XFW \
	SOI25BS0_IMX300 \
	SOI25BS1_color_ctrl_dat \
	SOI25BS1_dataflow_dat \
	SOI25BS1_debug_mgr_dat \
	SOI25BS1_exposure_ctrl_dat \
	SOI25BS1_exposure_ctrl_diagram_dat \
	SOI25BS1_exposure_ctrl_gamma_dat \
	SOI25BS1_face_detector_dat \
	SOI25BS1_flicker_detector_dat \
	SOI25BS1_focus_stats_conv_dat \
	SOI25BS1_food_comp_yummy_dat \
	SOI25BS1_food_detector_dat \
	SOI25BS1_hal_ctrl_dat \
	SOI25BS1_hal_ctrl_platform_dat \
	SOI25BS1_hal_ctrl_platform_abf_dat \
	SOI25BS1_hal_ctrl_platform_asf_lin_dat \
	SOI25BS1_hal_ctrl_platform_asf_stp_dat \
	SOI25BS1_hal_ctrl_platform_gic_dat \
	SOI25BS1_hdr_comp_dat \
	SOI25BS1_idt_ctrl_dat \
	SOI25BS1_image_conv_dat \
	SOI25BS1_image_conv_canele_dat \
	SOI25BS1_image_conv_marble_dat \
	SOI25BS1_image_conv_raisin_dat \
	SOI25BS1_image_conv_spica_dat \
	SOI25BS1_jpeg_enc_dat \
	SOI25BS1_lens_ctrl_dat \
	SOI25BS1_motion_estimation_dat \
	SOI25BS1_multiframe_nr_dat \
	SOI25BS1_multiframe_nr_melonpan_dat \
	SOI25BS1_multiframe_nr_mugichoco_dat \
	SOI25BS1_multiframe_nr_toppo_dat \
	SOI25BS1_object_tracker_dat \
	SOI25BS1_scene_detector_dat \
	SOI25BS1_snapshot_ctrl_dat \
	SOI25BS1_BU64747GWZ \
	SOI25BS1_BU64747GWZ_XCF \
	SOI25BS1_BU64747GWZ_XFW \
	SOI25BS1_IMX300 \
	SOI25BS2_color_ctrl_dat \
	SOI25BS2_dataflow_dat \
	SOI25BS2_debug_mgr_dat \
	SOI25BS2_exposure_ctrl_dat \
	SOI25BS2_exposure_ctrl_diagram_dat \
	SOI25BS2_exposure_ctrl_gamma_dat \
	SOI25BS2_face_detector_dat \
	SOI25BS2_flicker_detector_dat \
	SOI25BS2_focus_stats_conv_dat \
	SOI25BS2_food_comp_yummy_dat \
	SOI25BS2_food_detector_dat \
	SOI25BS2_hal_ctrl_dat \
	SOI25BS2_hal_ctrl_platform_dat \
	SOI25BS2_hal_ctrl_platform_abf_dat \
	SOI25BS2_hal_ctrl_platform_asf_lin_dat \
	SOI25BS2_hal_ctrl_platform_asf_stp_dat \
	SOI25BS2_hal_ctrl_platform_gic_dat \
	SOI25BS2_hdr_comp_dat \
	SOI25BS2_idt_ctrl_dat \
	SOI25BS2_image_conv_dat \
	SOI25BS2_image_conv_canele_dat \
	SOI25BS2_image_conv_marble_dat \
	SOI25BS2_image_conv_raisin_dat \
	SOI25BS2_image_conv_spica_dat \
	SOI25BS2_jpeg_enc_dat \
	SOI25BS2_lens_ctrl_dat \
	SOI25BS2_motion_estimation_dat \
	SOI25BS2_multiframe_nr_dat \
	SOI25BS2_multiframe_nr_melonpan_dat \
	SOI25BS2_multiframe_nr_mugichoco_dat \
	SOI25BS2_multiframe_nr_toppo_dat \
	SOI25BS2_object_tracker_dat \
	SOI25BS2_scene_detector_dat \
	SOI25BS2_snapshot_ctrl_dat \
	SOI25BS2_BU64747GWZ \
	SOI25BS2_BU64747GWZ_XCF \
	SOI25BS2_BU64747GWZ_XFW \
	SOI25BS2_IMX300 \
	SOI25BS3_color_ctrl_dat \
	SOI25BS3_dataflow_dat \
	SOI25BS3_debug_mgr_dat \
	SOI25BS3_exposure_ctrl_dat \
	SOI25BS3_exposure_ctrl_diagram_dat \
	SOI25BS3_exposure_ctrl_gamma_dat \
	SOI25BS3_face_detector_dat \
	SOI25BS3_flicker_detector_dat \
	SOI25BS3_focus_stats_conv_dat \
	SOI25BS3_food_comp_yummy_dat \
	SOI25BS3_food_detector_dat \
	SOI25BS3_hal_ctrl_dat \
	SOI25BS3_hal_ctrl_platform_dat \
	SOI25BS3_hal_ctrl_platform_abf_dat \
	SOI25BS3_hal_ctrl_platform_asf_lin_dat \
	SOI25BS3_hal_ctrl_platform_asf_stp_dat \
	SOI25BS3_hal_ctrl_platform_gic_dat \
	SOI25BS3_hdr_comp_dat \
	SOI25BS3_idt_ctrl_dat \
	SOI25BS3_image_conv_dat \
	SOI25BS3_image_conv_canele_dat \
	SOI25BS3_image_conv_marble_dat \
	SOI25BS3_image_conv_raisin_dat \
	SOI25BS3_image_conv_spica_dat \
	SOI25BS3_jpeg_enc_dat \
	SOI25BS3_lens_ctrl_dat \
	SOI25BS3_motion_estimation_dat \
	SOI25BS3_multiframe_nr_dat \
	SOI25BS3_multiframe_nr_melonpan_dat \
	SOI25BS3_multiframe_nr_mugichoco_dat \
	SOI25BS3_multiframe_nr_toppo_dat \
	SOI25BS3_object_tracker_dat \
	SOI25BS3_scene_detector_dat \
	SOI25BS3_snapshot_ctrl_dat \
	SOI25BS3_BU64747GWZ \
	SOI25BS3_BU64747GWZ_XCF \
	SOI25BS3_BU64747GWZ_XFW \
	SOI25BS3_IMX300 \
	SOI25BS4_color_ctrl_dat \
	SOI25BS4_dataflow_dat \
	SOI25BS4_debug_mgr_dat \
	SOI25BS4_exposure_ctrl_dat \
	SOI25BS4_exposure_ctrl_diagram_dat \
	SOI25BS4_exposure_ctrl_gamma_dat \
	SOI25BS4_face_detector_dat \
	SOI25BS4_flicker_detector_dat \
	SOI25BS4_focus_stats_conv_dat \
	SOI25BS4_food_comp_yummy_dat \
	SOI25BS4_food_detector_dat \
	SOI25BS4_hal_ctrl_dat \
	SOI25BS4_hal_ctrl_platform_dat \
	SOI25BS4_hal_ctrl_platform_abf_dat \
	SOI25BS4_hal_ctrl_platform_asf_lin_dat \
	SOI25BS4_hal_ctrl_platform_asf_stp_dat \
	SOI25BS4_hal_ctrl_platform_gic_dat \
	SOI25BS4_hdr_comp_dat \
	SOI25BS4_idt_ctrl_dat \
	SOI25BS4_image_conv_dat \
	SOI25BS4_image_conv_canele_dat \
	SOI25BS4_image_conv_marble_dat \
	SOI25BS4_image_conv_raisin_dat \
	SOI25BS4_image_conv_spica_dat \
	SOI25BS4_jpeg_enc_dat \
	SOI25BS4_lens_ctrl_dat \
	SOI25BS4_motion_estimation_dat \
	SOI25BS4_multiframe_nr_dat \
	SOI25BS4_multiframe_nr_melonpan_dat \
	SOI25BS4_multiframe_nr_mugichoco_dat \
	SOI25BS4_multiframe_nr_toppo_dat \
	SOI25BS4_object_tracker_dat \
	SOI25BS4_scene_detector_dat \
	SOI25BS4_snapshot_ctrl_dat \
	SOI25BS4_BU64747GWZ \
	SOI25BS4_BU64747GWZ_XCF \
	SOI25BS4_BU64747GWZ_XFW \
	SOI25BS4_IMX300 \
	default \
	flash \
	snapshot \
	streaming \
	supported \
	version
